[2025-09-13T02:52:14.365+0000] {processor.py:161} INFO - Started process (PID=185) to work on /opt/airflow/dags/3_dag_ejercicio_csv_faker.py
[2025-09-13T02:52:14.371+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/3_dag_ejercicio_csv_faker.py for tasks to queue
[2025-09-13T02:52:14.373+0000] {logging_mixin.py:188} INFO - [2025-09-13T02:52:14.373+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/3_dag_ejercicio_csv_faker.py
[2025-09-13T02:52:14.395+0000] {logging_mixin.py:188} INFO - [2025-09-13T02:52:14.388+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/3_dag_ejercicio_csv_faker.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/3_dag_ejercicio_csv_faker.py", line 2, in <module>
    from faker import Faker
ModuleNotFoundError: No module named 'faker'
[2025-09-13T02:52:14.396+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/3_dag_ejercicio_csv_faker.py
[2025-09-13T02:52:14.455+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/3_dag_ejercicio_csv_faker.py took 0.101 seconds
[2025-09-13T02:52:45.033+0000] {processor.py:161} INFO - Started process (PID=207) to work on /opt/airflow/dags/3_dag_ejercicio_csv_faker.py
[2025-09-13T02:52:45.034+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/3_dag_ejercicio_csv_faker.py for tasks to queue
[2025-09-13T02:52:45.041+0000] {logging_mixin.py:188} INFO - [2025-09-13T02:52:45.039+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/3_dag_ejercicio_csv_faker.py
[2025-09-13T02:52:45.054+0000] {logging_mixin.py:188} INFO - [2025-09-13T02:52:45.047+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/3_dag_ejercicio_csv_faker.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/3_dag_ejercicio_csv_faker.py", line 2, in <module>
    from faker import Faker
ModuleNotFoundError: No module named 'faker'
[2025-09-13T02:52:45.055+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/3_dag_ejercicio_csv_faker.py
[2025-09-13T02:52:45.181+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/3_dag_ejercicio_csv_faker.py took 0.167 seconds
[2025-09-13T02:53:16.044+0000] {processor.py:161} INFO - Started process (PID=234) to work on /opt/airflow/dags/3_dag_ejercicio_csv_faker.py
[2025-09-13T02:53:16.050+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/3_dag_ejercicio_csv_faker.py for tasks to queue
[2025-09-13T02:53:16.063+0000] {logging_mixin.py:188} INFO - [2025-09-13T02:53:16.061+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/3_dag_ejercicio_csv_faker.py
[2025-09-13T02:53:16.148+0000] {logging_mixin.py:188} INFO - [2025-09-13T02:53:16.107+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/3_dag_ejercicio_csv_faker.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/3_dag_ejercicio_csv_faker.py", line 2, in <module>
    from faker import Faker
ModuleNotFoundError: No module named 'faker'
[2025-09-13T02:53:16.151+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/3_dag_ejercicio_csv_faker.py
[2025-09-13T02:53:16.220+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/3_dag_ejercicio_csv_faker.py took 0.219 seconds
[2025-09-13T02:53:46.643+0000] {processor.py:161} INFO - Started process (PID=257) to work on /opt/airflow/dags/3_dag_ejercicio_csv_faker.py
[2025-09-13T02:53:46.647+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/3_dag_ejercicio_csv_faker.py for tasks to queue
[2025-09-13T02:53:46.665+0000] {logging_mixin.py:188} INFO - [2025-09-13T02:53:46.663+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/3_dag_ejercicio_csv_faker.py
[2025-09-13T02:53:46.732+0000] {logging_mixin.py:188} INFO - [2025-09-13T02:53:46.710+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/3_dag_ejercicio_csv_faker.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/3_dag_ejercicio_csv_faker.py", line 2, in <module>
    from faker import Faker
ModuleNotFoundError: No module named 'faker'
[2025-09-13T02:53:46.741+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/3_dag_ejercicio_csv_faker.py
[2025-09-13T02:53:47.072+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/3_dag_ejercicio_csv_faker.py took 0.478 seconds
[2025-09-13T02:54:17.684+0000] {processor.py:161} INFO - Started process (PID=282) to work on /opt/airflow/dags/3_dag_ejercicio_csv_faker.py
[2025-09-13T02:54:17.687+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/3_dag_ejercicio_csv_faker.py for tasks to queue
[2025-09-13T02:54:17.704+0000] {logging_mixin.py:188} INFO - [2025-09-13T02:54:17.701+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/3_dag_ejercicio_csv_faker.py
[2025-09-13T02:54:17.732+0000] {logging_mixin.py:188} INFO - [2025-09-13T02:54:17.721+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/3_dag_ejercicio_csv_faker.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/3_dag_ejercicio_csv_faker.py", line 2, in <module>
    from faker import Faker
ModuleNotFoundError: No module named 'faker'
[2025-09-13T02:54:17.736+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/3_dag_ejercicio_csv_faker.py
[2025-09-13T02:54:17.892+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/3_dag_ejercicio_csv_faker.py took 0.278 seconds
[2025-09-13T02:54:48.426+0000] {processor.py:161} INFO - Started process (PID=307) to work on /opt/airflow/dags/3_dag_ejercicio_csv_faker.py
[2025-09-13T02:54:48.428+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/3_dag_ejercicio_csv_faker.py for tasks to queue
[2025-09-13T02:54:48.434+0000] {logging_mixin.py:188} INFO - [2025-09-13T02:54:48.433+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/3_dag_ejercicio_csv_faker.py
[2025-09-13T02:54:48.450+0000] {logging_mixin.py:188} INFO - [2025-09-13T02:54:48.446+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/3_dag_ejercicio_csv_faker.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/3_dag_ejercicio_csv_faker.py", line 2, in <module>
    from faker import Faker
ModuleNotFoundError: No module named 'faker'
[2025-09-13T02:54:48.451+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/3_dag_ejercicio_csv_faker.py
[2025-09-13T02:54:48.504+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/3_dag_ejercicio_csv_faker.py took 0.106 seconds
[2025-09-13T02:55:19.317+0000] {processor.py:161} INFO - Started process (PID=332) to work on /opt/airflow/dags/3_dag_ejercicio_csv_faker.py
[2025-09-13T02:55:19.318+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/3_dag_ejercicio_csv_faker.py for tasks to queue
[2025-09-13T02:55:19.326+0000] {logging_mixin.py:188} INFO - [2025-09-13T02:55:19.323+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/3_dag_ejercicio_csv_faker.py
[2025-09-13T02:55:19.333+0000] {logging_mixin.py:188} INFO - [2025-09-13T02:55:19.331+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/3_dag_ejercicio_csv_faker.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/3_dag_ejercicio_csv_faker.py", line 2, in <module>
    from faker import Faker
ModuleNotFoundError: No module named 'faker'
[2025-09-13T02:55:19.334+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/3_dag_ejercicio_csv_faker.py
[2025-09-13T02:55:19.380+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/3_dag_ejercicio_csv_faker.py took 0.077 seconds
[2025-09-13T02:55:50.075+0000] {processor.py:161} INFO - Started process (PID=357) to work on /opt/airflow/dags/3_dag_ejercicio_csv_faker.py
[2025-09-13T02:55:50.078+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/3_dag_ejercicio_csv_faker.py for tasks to queue
[2025-09-13T02:55:50.085+0000] {logging_mixin.py:188} INFO - [2025-09-13T02:55:50.084+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/3_dag_ejercicio_csv_faker.py
[2025-09-13T02:55:50.099+0000] {logging_mixin.py:188} INFO - [2025-09-13T02:55:50.096+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/3_dag_ejercicio_csv_faker.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/3_dag_ejercicio_csv_faker.py", line 2, in <module>
    from faker import Faker
ModuleNotFoundError: No module named 'faker'
[2025-09-13T02:55:50.100+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/3_dag_ejercicio_csv_faker.py
[2025-09-13T02:55:50.159+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/3_dag_ejercicio_csv_faker.py took 0.120 seconds
[2025-09-13T02:56:20.729+0000] {processor.py:161} INFO - Started process (PID=382) to work on /opt/airflow/dags/3_dag_ejercicio_csv_faker.py
[2025-09-13T02:56:20.731+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/3_dag_ejercicio_csv_faker.py for tasks to queue
[2025-09-13T02:56:20.736+0000] {logging_mixin.py:188} INFO - [2025-09-13T02:56:20.735+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/3_dag_ejercicio_csv_faker.py
[2025-09-13T02:56:20.767+0000] {logging_mixin.py:188} INFO - [2025-09-13T02:56:20.754+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/3_dag_ejercicio_csv_faker.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/3_dag_ejercicio_csv_faker.py", line 2, in <module>
    from faker import Faker
ModuleNotFoundError: No module named 'faker'
[2025-09-13T02:56:20.770+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/3_dag_ejercicio_csv_faker.py
[2025-09-13T02:56:20.849+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/3_dag_ejercicio_csv_faker.py took 0.144 seconds
[2025-09-13T02:56:51.478+0000] {processor.py:161} INFO - Started process (PID=407) to work on /opt/airflow/dags/3_dag_ejercicio_csv_faker.py
[2025-09-13T02:56:51.481+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/3_dag_ejercicio_csv_faker.py for tasks to queue
[2025-09-13T02:56:51.484+0000] {logging_mixin.py:188} INFO - [2025-09-13T02:56:51.483+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/3_dag_ejercicio_csv_faker.py
[2025-09-13T02:56:51.498+0000] {logging_mixin.py:188} INFO - [2025-09-13T02:56:51.495+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/3_dag_ejercicio_csv_faker.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/3_dag_ejercicio_csv_faker.py", line 2, in <module>
    from faker import Faker
ModuleNotFoundError: No module named 'faker'
[2025-09-13T02:56:51.498+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/3_dag_ejercicio_csv_faker.py
[2025-09-13T02:56:51.570+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/3_dag_ejercicio_csv_faker.py took 0.116 seconds
[2025-09-13T02:57:21.871+0000] {processor.py:161} INFO - Started process (PID=437) to work on /opt/airflow/dags/3_dag_ejercicio_csv_faker.py
[2025-09-13T02:57:21.877+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/3_dag_ejercicio_csv_faker.py for tasks to queue
[2025-09-13T02:57:21.879+0000] {logging_mixin.py:188} INFO - [2025-09-13T02:57:21.878+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/3_dag_ejercicio_csv_faker.py
[2025-09-13T02:57:21.901+0000] {logging_mixin.py:188} INFO - [2025-09-13T02:57:21.891+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/3_dag_ejercicio_csv_faker.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/3_dag_ejercicio_csv_faker.py", line 2, in <module>
    from faker import Faker
ModuleNotFoundError: No module named 'faker'
[2025-09-13T02:57:21.903+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/3_dag_ejercicio_csv_faker.py
[2025-09-13T02:57:21.972+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/3_dag_ejercicio_csv_faker.py took 0.137 seconds
