[2025-09-13T06:59:13.853+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-09-13T06:59:14.126+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_2_export_kibana.ensure_index manual__2025-09-13T06:59:05.823951+00:00 [queued]>
[2025-09-13T06:59:14.197+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_2_export_kibana.ensure_index manual__2025-09-13T06:59:05.823951+00:00 [queued]>
[2025-09-13T06:59:14.200+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2025-09-13T06:59:14.264+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): ensure_index> on 2025-09-13 06:59:05.823951+00:00
[2025-09-13T06:59:14.316+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'dag_2_export_kibana', 'ensure_index', 'manual__2025-09-13T06:59:05.823951+00:00', '--job-id', '91', '--raw', '--subdir', 'DAGS_FOLDER/dag_2_export_kibana.py', '--cfg-path', '/tmp/tmpb7kgjobl']
[2025-09-13T06:59:14.329+0000] {standard_task_runner.py:91} INFO - Job 91: Subtask ensure_index
[2025-09-13T06:59:14.325+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=242) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-09-13T06:59:14.333+0000] {standard_task_runner.py:63} INFO - Started process 253 to run task
[2025-09-13T06:59:14.478+0000] {task_command.py:426} INFO - Running <TaskInstance: dag_2_export_kibana.ensure_index manual__2025-09-13T06:59:05.823951+00:00 [running]> on host c9e5a5421cb6
[2025-09-13T06:59:14.895+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dag_2_export_kibana' AIRFLOW_CTX_TASK_ID='ensure_index' AIRFLOW_CTX_EXECUTION_DATE='2025-09-13T06:59:05.823951+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-09-13T06:59:05.823951+00:00'
[2025-09-13T06:59:14.910+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-09-13T06:59:15.107+0000] {base.py:84} INFO - Using connection ID 'elasticsearch_default' for task execution.
[2025-09-13T06:59:15.184+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-09-13T06:59:15.185+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/dag_2_export_kibana.py", line 50, in _ensure_index
    es.indices.get(index=ES_INDEX)
    ^^^^^^^^^^
AttributeError: 'ESConnection' object has no attribute 'indices'
[2025-09-13T06:59:15.248+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=dag_2_export_kibana, task_id=ensure_index, run_id=manual__2025-09-13T06:59:05.823951+00:00, execution_date=20250913T065905, start_date=20250913T065914, end_date=20250913T065915
[2025-09-13T06:59:15.293+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 91 for task ensure_index ('ESConnection' object has no attribute 'indices'; 253)
[2025-09-13T06:59:15.360+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-09-13T06:59:15.493+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-09-13T06:59:15.496+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
